apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-jdbc-deployment
spec:
  selector:
    matchLabels:
      app: demo-jdbc
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-jdbc
    spec:
      containers:
        - name: demo-jdbc
          image: gcr.io/jfang-test/demo-jdbc
          envFrom:
            - secretRef:
                name: database-secret-jdbc
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 5
            failureThreshold: 5
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /ping
          readinessProbe:
            initialDelaySeconds: 5
            failureThreshold: 5
            timeoutSeconds: 5
            periodSeconds: 30
            httpGet:
              port: 8080
              path: /actuator/health
